
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dag_x_backend_development
test:
  <<: *default
  database: dag_x_backend_test

production:
  <<: *default
  database: dag_x_backend_production
  username: dag_x_backend
  password: <%= ENV["DAG_X_BACKEND_DATABASE_PASSWORD"] %>